Update the missing class test
The ClassNotFound exception which is thrown in case of a not existing
main class file is caught by Java Native Interface and java process
exits gracefully with an error message:

Error: Could not find or load main class MissingClassTest

It doesn't make sense to report such exceptions because this exception
would be reported every time when someone run "java foo" where 'foo'
does not exist.

Just for the record, ABRT doesn't detect the similar problem in python.

$ python foo
python: can't open file 'foo': [Errno 2] No such file or directory

Related to rhbz#1051198